# Generated by Django 5.0.2 on 2024-05-27 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcases',
            name='case_type',
            field=models.CharField(choices=[('Позитивный', 'Позитивный'), ('Негативный', 'Негативный')], default='Позитивный', max_length=10),
        ),
    ]
