# Generated by Django 5.0.2 on 2024-05-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_testcases_case_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreports',
            name='priority',
            field=models.CharField(choices=[('Высокий', 'Высокий'), ('Средний', 'Средний'), ('Низкий', 'Низкий')], default='Низкий', max_length=10),
        ),
        migrations.AlterField(
            model_name='bugreports',
            name='status',
            field=models.CharField(choices=[('Открыт', 'Открыт'), ('Закрыт', 'Закрыт'), ('В работе', 'В работе')], default='Открыт', max_length=10),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='priority',
            field=models.CharField(choices=[('Высокий', 'Высокий'), ('Средний', 'Средний'), ('Низкий', 'Низкий')], default='Низкий', max_length=10),
        ),
        migrations.AlterField(
            model_name='tester',
            name='role',
            field=models.CharField(choices=[('Руководитель тестирования', 'Руководитель тестирования'), ('Главный тестировщик', 'Главный тестировщик'), ('Тестировщик', 'Тестировщик')], default='Тестировщик', max_length=25),
        ),
        migrations.AlterField(
            model_name='testset',
            name='case_status',
            field=models.CharField(choices=[('Успешно', 'Успешно'), ('Провален', 'Провален'), ('Пропущен', 'Пропущен'), ('Не пройден', 'Не пройден')], default='Не пройден', max_length=10),
        ),
    ]
