# Generated by Django 5.0.2 on 2024-06-05 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_testcases_predictedresult_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaseSets',
        ),
    ]
