# Generated by Django 5.0.2 on 2024-05-27 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_bugreports_priority_alter_bugreports_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bugreports',
            old_name='case',
            new_name='testcase',
        ),
        migrations.RenameField(
            model_name='casesteps',
            old_name='case',
            new_name='testcase',
        ),
        migrations.RenameField(
            model_name='testcases',
            old_name='case_id',
            new_name='testcase_id',
        ),
        migrations.RenameField(
            model_name='testset',
            old_name='case',
            new_name='testcase',
        ),
    ]
