# Generated by Django 5.0.2 on 2024-06-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_casesets'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcases',
            name='case_file',
            field=models.FileField(blank=True, null=True, upload_to='testcases/'),
        ),
    ]
