# Generated by Django 5.0.2 on 2024-05-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_case_bugreports_testcase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testset',
            name='case_status',
        ),
        migrations.AddField(
            model_name='testcases',
            name='case_status',
            field=models.CharField(choices=[('Успешно', 'Успешно'), ('Провален', 'Провален'), ('Пропущен', 'Пропущен'), ('Не пройден', 'Не пройден')], default='Не пройден', max_length=10),
        ),
    ]
