# Generated by Django 5.0.2 on 2024-05-31 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_testset_case_status_testcases_case_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testset',
            name='testcase',
        ),
        migrations.AddField(
            model_name='testset',
            name='testcases',
            field=models.ManyToManyField(to='main.testcases'),
        ),
    ]
