# Generated by Django 5.0.2 on 2024-05-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_testset_testcase_testset_testcases'),
    ]

    operations = [
        migrations.AddField(
            model_name='testset',
            name='testset_name',
            field=models.CharField(default=11, max_length=128),
            preserve_default=False,
        ),
    ]
