# Generated by Django 5.0.2 on 2024-05-31 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_testset_testset_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bugreports',
            old_name='creationdate',
            new_name='creation_date',
        ),
    ]
