# Generated by Django 5.0.2 on 2024-05-31 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_testcases_predictedresult_testcases_step_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreports',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
