# Generated by Django 5.0.2 on 2024-05-31 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_bugreports_creation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugreports',
            name='testcase',
        ),
        migrations.AddField(
            model_name='bugreports',
            name='testcase',
            field=models.ManyToManyField(to='main.testcases'),
        ),
    ]
