# Generated by Django 5.0.2 on 2024-06-01 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_bugreports_testcase_bugreports_testcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreports',
            name='bug_file',
            field=models.FileField(blank=True, null=True, upload_to='bug_reports/'),
        ),
        migrations.AddField(
            model_name='testcases',
            name='case_file',
            field=models.FileField(blank=True, null=True, upload_to='testcases/'),
        ),
    ]
