# Generated by Django 5.0.2 on 2024-06-01 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_bugreports_bug_file_testcases_case_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testset',
            name='set',
        ),
    ]
