# Generated by Django 5.0.2 on 2024-06-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_testset_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=120)),
                ('position', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ExpectedResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=512)),
                ('position', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='testcases',
            name='predictedresult',
        ),
        migrations.RemoveField(
            model_name='testcases',
            name='step',
        ),
        migrations.AddField(
            model_name='testcases',
            name='steps',
            field=models.ManyToManyField(related_name='test_cases', to='main.casestep'),
        ),
        migrations.AddField(
            model_name='testcases',
            name='expected_results',
            field=models.ManyToManyField(related_name='test_cases', to='main.expectedresult'),
        ),
    ]
