# Generated by Django 5.0.2 on 2024-06-01 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_casestep_expectedresult_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestep',
            name='position',
        ),
        migrations.RemoveField(
            model_name='expectedresult',
            name='position',
        ),
    ]
