# Generated by Django 5.0.2 on 2024-06-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_testcases_expected_results_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcases',
            name='steps',
            field=models.TextField(max_length=120),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='expected_results',
            field=models.TextField(max_length=120),
        ),
        migrations.DeleteModel(
            name='CaseStep',
        ),
        migrations.DeleteModel(
            name='ExpectedResult',
        ),
    ]
