# Generated by Django 5.0.2 on 2024-06-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_testcases_expected_results_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcases',
            name='predictedresult',
            field=models.TextField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcases',
            name='step',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CaseSteps',
        ),
    ]
