# Generated by Django 5.0.2 on 2024-06-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_testcases_predictedresult_testcases_step_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcases',
            name='predictedresult',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='step',
            field=models.JSONField(default=list),
        ),
    ]
