# Generated by Django 5.0.2 on 2024-06-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_testcases_predictedresult_alter_testcases_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcases',
            name='case_status_local',
            field=models.CharField(choices=[('Успешно', 'Успешно'), ('Провален', 'Провален'), ('Пропущен', 'Пропущен'), ('Не пройден', 'Не пройден')], default='Не пройден', max_length=10),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='predictedresult',
            field=models.TextField(max_length=512),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='step',
            field=models.TextField(blank=True, null=True),
        ),
    ]
