# Generated by Django 5.0.2 on 2024-06-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_testcases_case_status_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcases',
            name='case_status_local',
            field=models.CharField(blank=True, choices=[('Успешно', 'Успешно'), ('Провален', 'Провален'), ('Пропущен', 'Пропущен'), ('Не пройден', 'Не пройден')], default='Не пройден', max_length=10, null=True),
        ),
    ]
