# Generated by Django 5.0.2 on 2024-06-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_testcases_case_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcases',
            name='predictedresult',
        ),
        migrations.RemoveField(
            model_name='testcases',
            name='step',
        ),
        migrations.AddField(
            model_name='testcases',
            name='predictedresult_0',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testcases',
            name='predictedresult_1',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testcases',
            name='predictedresult_2',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testcases',
            name='predictedresult_3',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testcases',
            name='predictedresult_4',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testcases',
            name='step_0',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testcases',
            name='step_1',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testcases',
            name='step_2',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testcases',
            name='step_3',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
