# Generated by Django 5.0.2 on 2024-06-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_testcases_predictedresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcases',
            name='step_4',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
