# Generated by Django 5.0.2 on 2024-06-03 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_testcases_step_4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcases',
            name='case_status_local',
        ),
    ]
