# Generated by Django 5.0.2 on 2024-06-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_testcases_case_status_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tester',
            name='project',
        ),
        migrations.AlterField(
            model_name='tester',
            name='role',
            field=models.CharField(choices=[('Главный тестировщик', 'Главный тестировщик'), ('Тестировщик', 'Тестировщик')], default='Тестировщик', max_length=25),
        ),
    ]
