# Generated by Django 5.0.2 on 2024-06-04 01:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_tester_project_alter_tester_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testset',
            name='runtime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
