# Generated by Django 5.0.2 on 2024-06-04 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_testset_runtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testset',
            name='runtime',
        ),
        migrations.AddField(
            model_name='testcases',
            name='runtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
