# Generated by Django 5.0.2 on 2024-06-04 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_testcases_runtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcases',
            old_name='predictedresult_0',
            new_name='predictedresult',
        ),
        migrations.RenameField(
            model_name='testcases',
            old_name='predictedresult_1',
            new_name='step',
        ),
        migrations.RemoveField(
            model_name='testcases',
            name='case_file',
        ),
        migrations.RemoveField(
            model_name='testcases',
            name='predictedresult_2',
        ),
        migrations.RemoveField(
            model_name='testcases',
            name='predictedresult_3',
        ),
        migrations.RemoveField(
            model_name='testcases',
            name='predictedresult_4',
        ),
        migrations.RemoveField(
            model_name='testcases',
            name='step_0',
        ),
        migrations.RemoveField(
            model_name='testcases',
            name='step_1',
        ),
        migrations.RemoveField(
            model_name='testcases',
            name='step_2',
        ),
        migrations.RemoveField(
            model_name='testcases',
            name='step_3',
        ),
        migrations.RemoveField(
            model_name='testcases',
            name='step_4',
        ),
        migrations.AlterField(
            model_name='bugreports',
            name='id',
            field=models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='id',
            field=models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testset',
            name='id',
            field=models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testset',
            name='testcases',
            field=models.ManyToManyField(blank=True, to='main.testcases'),
        ),
    ]
