# Generated by Django 5.0.2 on 2024-06-04 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_rename_predictedresult_0_testcases_predictedresult_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcases',
            name='runtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
