# Generated by Django 5.0.2 on 2024-06-04 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_testcases_runtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcases',
            name='runtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
