# Generated by Django 5.0.2 on 2024-05-14 22:36

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseSets',
            fields=[
                ('set_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('project_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('LD', 'Руководитель тестирования'), ('SN', 'Главный тестировщик'), ('DF', 'Тестировщик')], default='DF', max_length=2)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.projects')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('case_type', models.CharField(choices=[('FU', 'Функциональный'), ('NF', 'Нефункциональный')], default='FU', max_length=2)),
                ('priority', models.CharField(choices=[('HI', 'Высокий'), ('MD', 'Средний'), ('LW', 'Низкий')], default='LW', max_length=2)),
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('precondition', models.TextField(max_length=120)),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.projects')),
            ],
        ),
        migrations.CreateModel(
            name='CaseSteps',
            fields=[
                ('step_id', models.AutoField(primary_key=True, serialize=False)),
                ('step', models.TextField(blank=True, null=True)),
                ('predictedresult', models.TextField(max_length=512)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.testcases')),
            ],
        ),
        migrations.CreateModel(
            name='BugReports',
            fields=[
                ('status', models.CharField(choices=[('OP', 'Открыт'), ('CL', 'Закрыт'), ('IN', 'В работе')], default='OP', max_length=2)),
                ('priority', models.CharField(choices=[('HI', 'Высокий'), ('MD', 'Средний'), ('LW', 'Низкий')], default='LW', max_length=2)),
                ('bug_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, max_length=512, null=True)),
                ('creationdate', models.DateTimeField(default=datetime.datetime.now)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.projects')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.testcases')),
            ],
        ),
        migrations.CreateModel(
            name='TestSet',
            fields=[
                ('case_status', models.CharField(choices=[('SC', 'Провален'), ('FL', 'Успешно'), ('SP', 'Пропущен'), ('NP', 'Не пройден')], default='NP', max_length=2)),
                ('testset_id', models.AutoField(primary_key=True, serialize=False)),
                ('runtime', models.DateTimeField(blank=True, default=None, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.testcases')),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.casesets')),
            ],
        ),
    ]
