name: Docker Compose CI

on:
  push:
    branches: [ main ]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and run Docker Compose
      run: |
        docker-compose build
        docker-compose up -d

    - name: Make migrations
      run: |
        docker-compose run web python app/systemart/manage.py makemigrations
        docker-compose run web python app/systemart/manage.py migrate
